import os

# ── Simple .env loader ────────────────────────────────────────────────────────
def _load_env():
    if os.path.exists(".env"):
        with open(".env") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))
_load_env()

# ── API Keys ──────────────────────────────────────────────────────────────────
GROQ_API_KEY   = os.environ.get("GROQ_API_KEY",   "")
PEXELS_API_KEY = os.environ.get("PEXELS_API_KEY", "")

# ── Video format — vertical Shorts 9:16 ──────────────────────────────────────
VIDEO_WIDTH  = 1080
VIDEO_HEIGHT = 1920
FPS          = 30
NUM_FACTS    = 5

# ── Voice ─────────────────────────────────────────────────────────────────────
TTS_VOICE = "en-US-GuyNeural"
# TTS_VOICE = "en-US-JennyNeural"  # Female — uncomment to switch

# ── Background music ──────────────────────────────────────────────────────────
BACKGROUND_MUSIC_PATH   = "assets/bg_music.mp3"
BACKGROUND_MUSIC_VOLUME = 0.08

# ── Local scheduler ───────────────────────────────────────────────────────────
UPLOAD_TIME = "10:00"

# ── Paths ─────────────────────────────────────────────────────────────────────
OUTPUT_DIR = "output"
ASSETS_DIR = "assets"

# ── 365 Topics — one full year without repeating ─────────────────────────────
TOPICS = [

    # Space & Astronomy (30)
    "black holes",
    "the Big Bang theory",
    "neutron stars",
    "the James Webb Space Telescope discoveries",
    "Mars exploration",
    "the life cycle of stars",
    "dark matter and dark energy",
    "the International Space Station",
    "Jupiter and its moons",
    "the Milky Way galaxy",
    "supernovas",
    "the speed of light",
    "Saturn's rings",
    "exoplanets and alien worlds",
    "the moon and its effect on Earth",
    "solar flares and space weather",
    "the Voyager probes",
    "asteroids and meteor showers",
    "wormholes and space-time",
    "the Hubble Space Telescope",
    "comets throughout history",
    "space travel history",
    "the surface of Venus",
    "Pluto and the dwarf planets",
    "the aurora borealis",
    "cosmic radiation",
    "the Andromeda galaxy collision",
    "time dilation in space",
    "the coldest places in the universe",
    "how astronauts survive in space",

    # Ocean & Marine Life (25)
    "deep ocean creatures",
    "the Mariana Trench",
    "bioluminescent sea creatures",
    "whale intelligence and communication",
    "coral reef ecosystems",
    "the Great Barrier Reef",
    "octopus intelligence",
    "underwater volcanoes",
    "sea turtle migration",
    "the giant squid",
    "ocean currents and climate",
    "shark facts and myths",
    "deep sea hydrothermal vents",
    "jellyfish biology",
    "how fish navigate the ocean",
    "manta ray intelligence",
    "the blue whale — largest animal ever",
    "underwater caves and sinkholes",
    "sea horse facts",
    "electric eels and electric fish",
    "the pistol shrimp — fastest animal punch",
    "dolphin echolocation",
    "cuttlefish camouflage",
    "the mimic octopus",
    "how the ocean produces oxygen",

    # Human Body & Brain (25)
    "the human brain",
    "how memory works",
    "the human immune system",
    "how sleep works",
    "the human heart facts",
    "the gut microbiome",
    "how pain works",
    "the human eye and vision",
    "DNA and genetics",
    "how the liver works",
    "the power of the human nose",
    "how dreams work",
    "the lymphatic system",
    "how bones repair themselves",
    "the science of laughter",
    "how the ear and hearing work",
    "adrenaline and fight or flight",
    "the human skeleton",
    "how taste and smell are connected",
    "the science of ageing",
    "how the kidneys filter blood",
    "skin — the largest organ",
    "the science of goosebumps",
    "how humans regulate body temperature",
    "the appendix — what it actually does",

    # Animals & Nature (30)
    "animal superpowers",
    "animal camouflage",
    "insect world facts",
    "animal migration mysteries",
    "the intelligence of crows",
    "how ants build their colonies",
    "the world of fungi",
    "animal communication",
    "how spiders make silk",
    "the bombardier beetle",
    "tardigrades — the indestructible animal",
    "how bees make honey",
    "animal sleep habits",
    "platypus — the strange mammal",
    "how chameleons change color",
    "the mantis shrimp and its superpower eyes",
    "how wolves change rivers",
    "the axolotl and regeneration",
    "how plants communicate",
    "venomous animals",
    "the archerfish",
    "how termites build skyscrapers",
    "electric animals",
    "the immortal jellyfish",
    "how dogs understand humans",
    "the intelligence of elephants",
    "how birds navigate during migration",
    "rainforest secrets",
    "arctic and antarctic wildlife",
    "how snakes sense heat",

    # History & Ancient Civilizations (30)
    "ancient Egypt secrets",
    "ancient Rome facts",
    "ancient Greece discoveries",
    "the Maya civilization",
    "the Aztec empire",
    "the Inca civilization",
    "medieval history facts",
    "the Viking age",
    "the Mongol empire",
    "the Ottoman empire",
    "ancient China discoveries",
    "the Roman Colosseum",
    "lost civilizations",
    "ancient Indian civilizations",
    "the history of money",
    "the Black Death plague",
    "ancient warfare weapons",
    "the history of writing",
    "ancient Greek mythology facts",
    "the history of the calendar",
    "famous historical mysteries unsolved",
    "the history of democracy",
    "pirates throughout history",
    "the history of medicine",
    "ancient Egyptian mummies",
    "the Silk Road trade route",
    "the history of salt — why it was gold",
    "the history of spices",
    "famous ancient libraries",
    "the real history of ninjas",

    # Science & Physics (25)
    "quantum physics facts",
    "the theory of relativity",
    "how nuclear energy works",
    "the laws of thermodynamics",
    "the history of electricity",
    "magnetism facts",
    "how lasers work",
    "the science of sound",
    "superconductors",
    "the periodic table secrets",
    "how radioactivity works",
    "the science of color",
    "how gravity works",
    "the science of fire",
    "plasma — the fourth state of matter",
    "how mirrors work",
    "the science of ice",
    "how rainbows form",
    "the science of explosions",
    "how semiconductors changed the world",
    "the science of friction",
    "how wifi and radio waves work",
    "the science behind lightning",
    "how vaccines work",
    "the science of pressure",

    # Psychology & Mind (20)
    "psychology tricks and mind hacks",
    "cognitive biases that fool your brain",
    "the placebo effect",
    "how habits form in the brain",
    "the science of fear",
    "body language secrets",
    "how advertising manipulates the brain",
    "the science of addiction",
    "how stress affects the body",
    "the power of music on the brain",
    "the science of creativity",
    "how loneliness affects the body",
    "the Dunning-Kruger effect",
    "the science of motivation",
    "optical illusions and the brain",
    "how colors affect emotions",
    "the power of smell and memory",
    "the science of boredom",
    "how laughter affects health",
    "the science of decision making",

    # Technology & AI (20)
    "AI and technology facts",
    "how the internet works",
    "the history of computers",
    "quantum computing",
    "how GPS works",
    "blockchain and cryptocurrency basics",
    "how robots are built",
    "the history of the smartphone",
    "how touchscreens work",
    "3D printing revolution",
    "how social media algorithms work",
    "the dark web facts",
    "cybersecurity and hacking",
    "how electric cars work",
    "the history of video games",
    "how search engines work",
    "the future of virtual reality",
    "how facial recognition works",
    "drone technology facts",
    "how nuclear bombs work",

    # Earth & Geography (25)
    "world geography facts",
    "volcanoes and eruptions",
    "earthquakes and tectonic plates",
    "extreme weather events",
    "the Amazon rainforest",
    "deserts of the world",
    "the world's deepest lakes",
    "how mountains form",
    "the Dead Sea facts",
    "underground rivers and caves",
    "the Sahara desert secrets",
    "how glaciers work",
    "the world's largest caves",
    "rivers that flow uphill",
    "bizarre geographical facts",
    "the world's most extreme environments",
    "how sinkholes form",
    "the poles and magnetic north",
    "how soil is formed",
    "the world's rarest natural phenomena",
    "tsunami science",
    "how tornadoes form",
    "the world's highest mountains",
    "how the Grand Canyon formed",
    "bizarre weather phenomena",

    # Mathematics & Logic (15)
    "mathematics facts that break your brain",
    "the history of zero",
    "infinity in mathematics",
    "prime numbers and their mysteries",
    "the Fibonacci sequence in nature",
    "famous unsolved math problems",
    "the golden ratio",
    "how probability works",
    "geometry in nature",
    "the history of pi",
    "fractals and chaos theory",
    "game theory",
    "cryptography and secret codes",
    "how statistics can lie",
    "the mathematics of music",

    # Food & Bizarre Facts (20)
    "bizarre food facts",
    "the science of cooking",
    "history of chocolate",
    "why spicy food feels hot",
    "fermentation and how cheese is made",
    "the history of bread",
    "how coffee affects the brain",
    "bizarre food laws around the world",
    "the history of sugar",
    "how alcohol affects the body",
    "the science of taste",
    "poisonous foods we eat every day",
    "the history of ice cream",
    "how tea became the world's drink",
    "the most expensive foods in the world",
    "why we crave junk food",
    "the history of fast food",
    "how honey never expires",
    "bizarre eating habits of animals",
    "the science of hunger",

    # Records & Extremes (20)
    "bizarre world records",
    "the fastest things on Earth",
    "the strongest materials known",
    "the hottest and coldest places on Earth",
    "the world's most dangerous places",
    "the oldest living things on Earth",
    "extreme survival stories",
    "the deepest places on Earth",
    "the biggest things ever built",
    "the world's most venomous creatures",
    "the loudest sounds ever recorded",
    "the smallest living organisms",
    "the world's most isolated places",
    "the most valuable things on Earth",
    "the rarest elements on Earth",
    "the world's biggest explosions in history",
    "the longest living humans in history",
    "the highest jumps in nature",
    "the world's fastest growing plants",
    "extreme human endurance records",

    # More Space (10)
    "how telescopes work",
    "space junk and satellite pollution",
    "the concept of multiverse",
    "pulsars and magnetars",
    "how rocket engines work",
    "the largest known star",
    "how solar panels work in space",
    "space food and astronaut diet",
    "the science of re-entry into atmosphere",
    "how black holes are detected",

    # More Animals (10)
    "how parrots mimic speech",
    "the intelligence of pigs",
    "how salmon find their way home",
    "how fireflies produce light",
    "the secret life of trees",
    "how caterpillars become butterflies",
    "the power of ant supercolonies",
    "how whales sing",
    "animal architects and amazing structures",
    "how sharks have survived 450 million years",

    # More Human Body (10)
    "how the human voice works",
    "the science of hiccups",
    "how twins are formed",
    "the science of sneezing",
    "how the body fights cancer naturally",
    "the science of blushing",
    "how the body produces energy",
    "the science of yawning",
    "how reflexes work",
    "the science of left and right handedness",

    # More History (10)
    "the history of warfare and weapons",
    "women who changed history",
    "the history of clocks and timekeeping",
    "how ancient Egyptians built pyramids",
    "the history of ships and navigation",
    "famous ancient engineering feats",
    "how ancient people understood astronomy",
    "the history of ancient trade routes",
    "the history of writing systems",
    "secret societies throughout history",

    # More Science (10)
    "how vaccines were discovered",
    "the science of glass",
    "how plastic is made",
    "the science of rust and corrosion",
    "how anesthesia works",
    "the science of soap and cleaning",
    "how paper is made",
    "the science of adhesives and glue",
    "how the microwave was invented by accident",
    "the science of supercooling",

    # More Technology (10)
    "how nuclear reactors work",
    "the history of aviation",
    "how submarines work",
    "the history of photography",
    "how radio was invented",
    "the science of batteries",
    "how satellites orbit Earth",
    "the history of the printing press",
    "how MRI machines work",
    "the science of fiber optics",

    # More Earth (10)
    "the world's strangest rock formations",
    "how caves and stalactites form",
    "the history of Earth's ice ages",
    "how sand dunes move",
    "the science of tides",
    "the world's most active volcanoes",
    "how rivers carve canyons",
    "the science of fog and clouds",
    "natural wonders of the world",
    "how lightning shapes the landscape",

    # Bonus mixed (10)
    "the science of music and sound waves",
    "how languages evolve and die",
    "the history of architecture",
    "how myths and legends spread",
    "the science of luck and coincidence",
    "how the stock market actually works",
    "the history of sports",
    "how fashion has changed history",
    "the science behind superstitions",
    "how maps changed the world",

]

print(f"[Config] Loaded {len(TOPICS)} topics")
